import { describe, expect, it } from 'vitest';
import type { WeatherRow } from '@/lib/dwd/product';
import { compose } from './compose';
import { PITCH_OFFSET, clamp } from './scales';
import oracle from './__fixtures__/python_oracle.json';

/**
 * Diffs this port against the Python it was ported from.
 *
 * `__fixtures__/python_oracle.json` is generated by `__fixtures__/oracle.py`,
 * which runs upstream's own `produce_midi_file` over 180 synthetic observations
 * spanning all four seasons, both signs of the pressure gradient, all four
 * bass-volume bands, and readings past every clamp. Regenerate it with:
 *
 *     python3 lib/soni/__fixtures__/oracle.py
 *
 * (the script expects the upstream repo checked out beside it).
 *
 * The unit tests above assert what I believe the rules to be. This one asserts
 * that belief matches the original — a distinction that matters, because the
 * rules are the whole artistic content of the project and a plausible-looking
 * misreading would still pass tests I wrote from the same misreading.
 */

type OracleNote = {
  track: number;
  pitch: number;
  time: number;
  duration: number;
  velocity: number;
};

const rows = oracle.rows as WeatherRow[];
const pythonNotes = oracle.notes as OracleNote[];

/**
 * The one intentional difference, applied to the reference before comparing.
 *
 * Upstream's note table is an octave below the MIDI standard, so its pitches
 * are shifted up by PITCH_OFFSET here. The clamp is applied *after* the shift
 * on both sides, which is why the oracle records unclamped pitches: moving the
 * whole piece up an octave changes which notes reach the bottom of the range,
 * and that has to stay visible rather than being hidden by pre-clamped input.
 */
const expectedPitch = (pitch: number) => clamp(pitch + PITCH_OFFSET, 0, 127);

describe('parity with the original Python', () => {
  const composed = compose(rows, { velMin: 30, velMax: 127 });

  it('has a fixture that actually exercises the interesting branches', () => {
    expect(rows.length).toBe(180);
    expect(pythonNotes.length).toBeGreaterThan(300);

    // All five tracks, including rain, must be represented or the comparison
    // would silently cover less than it appears to.
    expect(new Set(pythonNotes.map((n) => n.track))).toEqual(new Set([0, 1, 2, 3, 4]));
  });

  it('emits exactly the same number of notes', () => {
    expect(composed.notes.length).toBe(pythonNotes.length);
  });

  it('emits identical notes, in identical order', () => {
    const actual = composed.notes.map((n) => ({
      track: n.track,
      pitch: n.pitch,
      time: Number(n.time.toFixed(6)),
      duration: Number(n.duration.toFixed(6)),
      velocity: n.velocity,
    }));

    const expected = pythonNotes.map((n) => ({
      track: n.track,
      pitch: expectedPitch(n.pitch),
      time: Number(n.time.toFixed(6)),
      duration: Number(n.duration.toFixed(6)),
      velocity: n.velocity,
    }));

    expect(actual).toEqual(expected);
  });

  it('agrees on total length in beats', () => {
    // Measured from the melody track, which is the one track that emits exactly
    // one note per step at the step boundary. Other tracks overrun their slot
    // by design — a held chord runs nine beats — so the last onset overall says
    // nothing about where the piece ends.
    const lastMelodyOnset = Math.max(
      ...pythonNotes.filter((n) => n.track === 0).map((n) => n.time),
    );
    expect(composed.beats).toBe(lastMelodyOnset + 3);
  });

  it('agrees on velocity for every track independently', () => {
    for (const track of [0, 1, 2, 3, 4]) {
      const mine = composed.notes.filter((n) => n.track === track).map((n) => n.velocity);
      const theirs = pythonNotes.filter((n) => n.track === track).map((n) => n.velocity);
      expect(mine, `track ${track}`).toEqual(theirs);
    }
  });
});
